name: Build ESP Dylib
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Theos
        run: |
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS14.4.sdk.tar.xz
          tar -xf iPhoneOS14.4.sdk.tar.xz -C $THEOS/sdks
          rm iPhoneOS14.4.sdk.tar.xz

      - name: Build Dylib
        run: |
          export THEOS=~/theos
          make package
          
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: MyESP-Dylib
          path: packages/*.deb
